### ISSUE TITLE
2021年9月1日更新后 TS失效,附临时解决方法

### ISSUE THREAD

**Issue by Weltolk** [lesuixin/Hearthstone-Hearthbuddy#15]
先正常点击start启动,缓存好卡组信息然后报错自动停止后,手动点传统对战,进到选卡组匹配的界面,再点击start启动即可.已经测试过了,游戏结束后会自动开始下一局

**Comment by lesuixin** [comment]
用TS.v1.7里◆TS正式版 .exe DONOTDELETE.bin 替换TS.1.6也行
