### ISSUE TITLE
选牌界面出现这个错误

### ISSUE THREAD

**Issue by Lonelyleavesi** [lesuixin/Hearthstone-Hearthbuddy#18]
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\Desktop\Bots\DefaultBot\SettingsGui.xaml'.
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   在 System.IO.FileStream..ctor(String path, FileMode mode)
   在 Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.get_Control()
   在 Hearthbuddy.Windows.MainWindow.fmA2RFqpyr(Object  )
   在 Hearthbuddy.Windows.MainWindow.knV2vB2e1H()
   在 System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback)
   在 Hearthbuddy.Windows.MainWindow.EOK2Bqu5yQ(Object  )

**Comment by lengsaoman** [comment]
+1
