### ISSUE TITLE
选牌阶段停止bug，求大佬解答，更新最新Java环境

### ISSUE THREAD

**Issue by lengsaoman** [lesuixin/Hearthstone-Hearthbuddy#21]
[勾选] 执行过程中出现异常：Buddy.Coroutines.CoroutineUnhandledException: Exception was thrown by coroutine ---> System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 HREngine.Bots.DefaultRoutine.<MulliganLogic>d__12.MoveNext() 位置 c:\Users\张需鹏\Desktop\TS正式版 v1.7(整合最新策略)\Routines\DefaultRoutine\DefaultRoutine.cs:行号 748
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 HREngine.Bots.DefaultRoutine.<Logic>d__3.MoveNext() 位置 c:\Users\张需鹏\Desktop\TS正式版 v1.7(整合最新策略)\Routines\DefaultRoutine\DefaultRoutine.cs:行号 641
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.<method_34>d__78__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 EPa9ZvYBYqEHaUgwQ3q.wkDYx7GSh(TaskAwaiter& , EPa9ZvYBYqEHaUgwQ3q )
   在 Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.<method_39>d__83__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 EPa9ZvYBYqEHaUgwQ3q.wkDYx7GSh(TaskAwaiter& , EPa9ZvYBYqEHaUgwQ3q )
   在 Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.<method_32>d__76__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 EPa9ZvYBYqEHaUgwQ3q.wkDYx7GSh(TaskAwaiter& , EPa9ZvYBYqEHaUgwQ3q )
   在 Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.<method_21>d__65__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 EPa9ZvYBYqEHaUgwQ3q.wkDYx7GSh(TaskAwaiter& , EPa9ZvYBYqEHaUgwQ3q )
   在 Buddy.Coroutines.Coroutine.<>c__DisplayClass37_0.kFLvk6o8w5rEkuxmkEt.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Buddy.Coroutines.Coroutine.yW15YSUhbt(Boolean  )
   在 Buddy.Coroutines.Coroutine.HxR5rqUxtE(Boolean  )
   在 Buddy.Coroutines.Coroutine.Resume()
   在 Triton.Bot.Logic.Bots.DefaultBot.DefaultBot.Tick()
   在 Triton.Bot.BotManager.rkEjp6mGS8(IBot  )

[自动停止插件] 停止运行

**Comment by lesuixin** [comment]
游戏更新，注意个人隐私
