### ISSUE TITLE
请问可以出个修复旧版本的教程吗？只修复了第一个问题

### ISSUE THREAD

**Issue by liaohaifei** [lesuixin/Hearthstone-Hearthbuddy#3]

**Comment by lesuixin** [comment]
不会修复，github搜索maxioriv，github search for maxioriv

**Comment by liaohaifei** [comment]
看就是用他的hb4_16修复的第一个问题，后面的搞了很久还是没搞好。

**Comment by liaohaifei** [comment]
> 不会修复，github搜索maxioriv，github search for maxioriv

就是用他的hb4_16修复的第一个问题，后面的搞了很久还是没搞好。
