### ISSUE TITLE
求问贴吧4.1折腾版的json字段都是什么

### ISSUE THREAD

**Issue by Huangyan0804** [lesuixin/Hearthstone-Hearthbuddy#4]
有没有知道的说一下

**Comment by Ray8876** [comment]
fiddler自己抓了看一下 0改1就行

**Comment by Huangyan0804** [comment]
> fiddler自己抓了看一下 0改1就行

抓了只有404，json文件被删除了

**Comment by Ray8876** [comment]
抓包能抓到一条请求是https://gitee.com/yl-hb/check_hb/raw/master/%2020210401check.json
内容是{"state": "0", "tips": "版本关停"}

所以：
新建一个autoResponder
EXACT:https://gitee.com/yl-hb/check_hb/raw/master/%2020210401check.json
内容是{"state": "1", "tips": ""}

**Comment by Huangyan0804** [comment]
> 抓包能抓到一条请求是https://gitee.com/yl-hb/check_hb/raw/master/%2020210401check.json
> 内容是{"state": "0", "tips": "版本关停"}
> 
> 所以：
> 新建一个autoResponder
> EXACT:https://gitee.com/yl-hb/check_hb/raw/master/%2020210401check.json
> 内容是{"state": "1", "tips": ""}

谢谢大佬
