### ISSUE TITLE
使用中控时，打开兄弟但是不会自动开始，搜了下bat启动器的解决办法，请问大佬可以在 2021.4.1贴吧折腾启动器.exe 里添加类似命令吗？谢谢！

### ISSUE THREAD

**Issue by h619062083** [lesuixin/Hearthstone-Hearthbuddy#7]
感谢大佬分享！！！同时有个情况想向大佬请教下。

使用贴吧折腾版的中控时，路径设置为”2021.4.1贴吧折腾启动器.exe“，可以打开兄弟，但不会自动开始运行，找了下中控使用说明里有适用于”启动器.bat“的如下说明，请问大佬可以在”2021.4.1贴吧折腾启动器.exe“里进行类似处理吗？谢谢大佬！

打开兄弟后不会自动开始

原因是使用启动器启动兄弟，中控发送的自动开始参数没有经过启动器传到兄弟中。解决办法：在启动器中 start Hearthbuddy.exe 一行改为 start Hearthbuddy.exe %1 %2 。（不影响正常启动）

启动器

@echo off
set d=%date%
cd /d %~dp0
::此处通常设置为兄弟版本后一天
date 2021-4-2
::此处后面注意添加%1 %2用以传递自动开始的参数
start Hearthbuddy.exe %1 %2
ping 127.0.0.1 -n 5 >nul
date %d%
exit
存储为 .bat 格式。

**Comment by Achss** [comment]
同问

**Comment by Achss** [comment]
同问，在2021.4.1贴吧折腾启动器的txt文件中找不到start Hearthbuddy.exe，添加不了%1 %2
