### ISSUE TITLE
TS版没有打完停止按键 ？

### ISSUE THREAD

**Issue by HXChow** [lesuixin/Hearthstone-Hearthbuddy#9]
如题 试了一下需要手动停止

**Comment by lesuixin** [comment]
从贴吧折腾版本复制\Plugins\AutoStop粘贴到\Plugins

**Comment by HXChow** [comment]
> 从贴吧折腾版本复制\Plugins\AutoStop粘贴到\Plugins

贴吧4.1折腾版本Plugins文件夹底下没见到有AutoStop 也未搜索到相关关键词
